### ISSUE TITLE
Fail compiling

### ISSUE THREAD

**Issue by realharley91** [howCodeORG/flo#1]
When I do `go build` it gives me an error. I don't know if it's problem with my setup since I don't use go too often on my machine. But here's the output:

``` sh
➜  flo git:(master) go build
main.go:14:2: cannot find package "flo/compiler" in any of:
	/usr/lib64/golang/src/flo/compiler (from $GOROOT)
	/home/flurach/go/src/flo/compiler (from $GOPATH)
main.go:15:2: cannot find package "flo/parser" in any of:
	/usr/lib64/golang/src/flo/parser (from $GOROOT)
	/home/flurach/go/src/flo/parser (from $GOPATH)
main.go:4:2: cannot find package "flo/vm" in any of:
	/usr/lib64/golang/src/flo/vm (from $GOROOT)
	/home/flurach/go/src/flo/vm (from $GOPATH)
```

How can I fix this?

**Comment by howCodeORG** [comment]
Hi!

Make sure you've download Flo to your GOPATH.

Your go path is the folder where you should store all your Go projects. On macOS your GOPATH should be `/Users/<yourname>/go/`.

When you download Flo, rename `flo-master` to `flo` and put `flo` in this folder: `/Users/<yourname>/go/src/`.

Then make sure you've installed the dependencies listed in the readme and then `go build` should work.

**Comment by realharley91** [comment]
Thanks! Now it's working properly. You might get a pull request soon 😏
